flask_blog/models.py
from datetime import datetime
from flask_login import UserMixin
from flask_blog import db, login_manager


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False,
                           default='default.png')
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    #В SQLAlchemy атрибуты модели (username, email, password и т.д.) создаются через db.Column(),
    # а не через обычный конструктор Python с параметрами.
    # По умолчанию класс User не имеет явно определённого метода __init__,
    # принимающего эти аргументы, поэтому IDE может считать,
    # что такие параметры при создании объекта недопустимы. Решение ↓ создать __init__
    def __init__(self, username, email, password, image_file='default.png'):
        self.username = username
        self.email = email
        self.password = password
        self.image_file = image_file

    def __repr__(self):
        return f"Пользователь('{self.username}, " \
               f"{self.email}', '{self.image_file}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False,
                            default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'),
                        nullable=False)

    def __repr__(self):
        return f"Запись('{self.title}', '{self.date_posted}')"


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

flask_blog/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from flask_blog.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Имя пользователя:',
                           validators=[DataRequired(),
                                       Length(min=2, max=20)])
    email = StringField('Email:',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Пароль:', validators=[DataRequired()])
    confirm_password = PasswordField('Подтвердить пароль',
                                     validators=[DataRequired(),
                                                 EqualTo('password')])
    submit = SubmitField('Зарегистрироваться')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError(
                'Это имя занято. Пожалуйста, выберите другое.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError(
                'Этот email занят. Пожалуйста, выберите другой.')


class LoginForm(FlaskForm):
    email = StringField('Email:',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Пароль:', validators=[DataRequired()])
    remember = BooleanField('Напомнить пароль')
    submit = SubmitField('Войти')


class UpdateAccountForm(FlaskForm):
    username = StringField('Имя пользователя',
                           validators=[DataRequired(),
                                       Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    picture = FileField('Обновить фото профиля',
                        validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Обновить')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('Это имя занято. '
                                      'Пожалуйста, выберите другое')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('Этот email занят'
                                      'Пожалуйста, выберите другой')


class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Изменить пароль')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('Аккаунт с данным email-адресом '
                                  'отсутствует. '
                                  'Вы можете зарегистрировать его')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Пароль:', validators=[DataRequired()])
    confirm_password = PasswordField('Подтвердите пароль',
                                     validators=[DataRequired(),
                                                 EqualTo('password')])
    submit = SubmitField('Переустановить пароль')

flask_blog/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_blog.config import Config

db = SQLAlchemy()
login_manager = LoginManager()
bcrypt = Bcrypt()    # создаём объект расширения без привязки к app


def create_app():
    app = Flask(__name__)

    # 1️⃣ Сначала загружаем конфигурацию!
    app.config.from_object(Config)

    # 2️⃣ Потом инициализируем расширения
    db.init_app(app)
    login_manager.init_app(app)

    # 3️⃣ Регистрируем Blueprint'ы
    from flask_blog.main.routes import main
    app.register_blueprint(main)

    from flask_blog.users.routes import users
    app.register_blueprint(users)
    # db.init_app(app) требует,
        # чтобы SQLALCHEMY_DATABASE_URI уже был задан в app.config.

    bcrypt.init_app(app)     # Метод init_app(app) связывает объект bcrypt с конкретным приложением Flask,
                            # позволяя использовать его методы (generate_password_hash,
                            # check_password_hash и т.д.) внутри этого приложения

    return app

flask_blog/main/routes.py
from flask import render_template, Blueprint
from flask_blog.models import User

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')

flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm)

from flask_blog.users.utils import save_picture

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # После хеширования вернутся, байты - их надо декодировать в строку ↑

        # Здесь создаём пользователя с hashed_password в базе данных:
        user = User(username=form.username.data,    # User - это SQLAlchemy-модель пользователя (в models.py)
                    email=form.email.data, password=hashed_password)
        # Параметры созданного объекта-пользователя
        # посредством ORM-библиотеки SQLAlchemy будут передаваться в базу данных и сохраняться:
        db.session.add(user)    #   сессия Flask-SQLAlchemy
        db.session.commit()     # объект, который представляет собой транзакцию базы данных
        flash('Ваша учетная запись была создана!'
              ' Теперь вы можете войти в систему', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)

flask_blog/templates/home.html
{% extends "layout.html" %}

{% block style %}
    <style>   
        body{
        z-index: 5;
        }

        body:before {
        content: ' ';
        display: block;
        position: fixed;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        object-fit: contain;
        z-index: 1;
        opacity: 0.5;
        background-image: url('../static/images/bg.jpg');
        /* background-repeat: no-repeat; */
        /* background-position: 50% 0; */
        background-size: cover;
        }

        .navbar{ 
            background-color: #e2cfc4;
            box-shadow: 0px 1px 10px black;
        }

        .container{
            position: relative;
            z-index: 5;
        }
        
        .heading > h1{
            font-size: 55px;
            font-family: 'Alice', serif;
            color: black;
            text-shadow: 2px 2px #a44a3f;
        }

        .card-text{
            text-align: justify;
            color: rgb(43, 37, 37);
            font-weight: 500;
            font-size: 22px;
        }

        .container > button{
            color: blue;
            padding: 7px;
            border:1px solid blue;
            border-radius: 5px;
            transition: 0.3s ease; 
        }

        .container > button:hover{
            color: white;
            background-color: blue;
            /* padding: 5px; */
        }
    </style>
{% endblock style %}

{% block content %}
<div class="container" style="margin: 12rem 4rem; text-align: center;">
    <div class="heading">
        <h1>ДОБРО ПОЖАЛОВАТЬ!📝</h1>
    </div>
    <hr class="w3-border-grey" style="margin:auto; width:40%;">
    <br>
    <div class="content-body">
        <p class="card-text" id="para">Добро пожаловать в мой <strong><em> блог!</em></strong>
            Большое спасибо за посещение. Я рад видеть вас на просторах моего блога! Это так здорово видеть
            вас здесь. Позвольте мне сказать вам одну вещь: вы можете не только просматривать
            новые посты, но и получать обновления...😄</p>
    </div>
    <br>

    
    <!-- <div class="card" style="border-bottom-left-radius: 50px; border-top-right-radius: 50px; background-color:  #2ec4b6; box-shadow: 10px 15px 10px lightslategray;">
        <div class="card-body" style="color: white;">
            <br>
        </div>
    </div> -->
</div>
{% endblock content %}

flask_blog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Alice&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">

    {% if title %}
        <title>Flask-блог - {{ title }}</title>
    {% else %}
        <title>Flask-блог</title>
    {% endif %}

    {% block head %} {% endblock head %}

    <style>
      body{
        background-color: #e5e5e5;
        margin-top: 6.5rem;
      }

      .navigation-links{
        color: white !important;
        font-weight: 500;
        background-color: rgb(183, 214, 252);
        border-radius: 5px;
        border-bottom: 4px solid blue;
        margin: 5px;
        background-size: 200% 200%;
        background-image: linear-gradient( transparent 50%, rgb(79, 128, 233) 50%);
        transition: background-position 300ms, color 300ms ease, border-color 300ms ease;      
      }

      .navigation-links:hover{
        color: white;
        background-image: linear-gradient( transparent 50%, #3a86ff 50%);
        background-position: 0% 100%;
      }

      .navbar{
        background-color: #c6def1; 
        box-shadow: 0px 1px 10px black;
      }

      .navbar .container{
        margin-bottom: 0;
      }
    </style>

    
  {% block style %} {% endblock style %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/" style="color: rgb(7, 85, 173); font-family: 'Lobster', cursive; font-weight: 800; font-size: 30px;">Мой блог</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          {% if current_user.is_authenticated %}
            <h4>Привет, {{current_user.username }}!</h4>
          {% else %}
            <a class="nav-link nav-item navigation-links" href="{{ url_for('users.register') }}">Зарегистрироваться</a>

          {% endif %}
          <div class="collapse navbar-collapse" id="navbarToggle" style="justify-content: flex-end;">
            <!-- Navbar Right Side -->

          </div>
        </div>
      </nav>
    </header>
    
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-10">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>